version: '3.8'
services:
  mytheresa:
    build: 
      context: .
      target: mytheresa
    ports:
      - 8000:8000
    depends_on:
      mongodb:
        condition: service_healthy
    command: |
      /bin/sh -c "/mytheresa/mytheresa"
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017" 
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./entrypoint-mongodb:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_DATABASE: mytheresadb
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8001:8080"
    depends_on: 
      - mytheresa
    environment:
      - SWAGGER_JSON=/mytheresa/docs/swagger.json
    volumes:
      - ./docs:/mytheresa/docs